# Generated by Django 5.1.4 on 2025-05-10 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "booking",
            "0006_remove_seat_seat_type_bus_surcharge_route_base_price_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Cancelled", "Cancelled"),
                    ("Completed", "Completed"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_method",
            field=models.CharField(
                choices=[("QR", "QR"), ("AtStation", "At Station")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Failed", "Failed"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
