# Generated by Django 5.1.4 on 2025-05-10 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_booking_booking_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="seat",
        ),
        migrations.CreateModel(
            name="BookingSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_seats",
                        to="booking.booking",
                    ),
                ),
                (
                    "seat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="booking.seat"
                    ),
                ),
            ],
            options={
                "unique_together": {("booking", "seat")},
            },
        ),
    ]
